import { SaleInvoice, PurchaseInvoice, AppSettings } from '../types';

export const formatInvoiceWhatsAppText = (
  invoice: SaleInvoice | PurchaseInvoice,
  isPurchase: boolean,
  settings: AppSettings
) => {
  const sale = !isPurchase ? (invoice as SaleInvoice) : null;
  const purchase = isPurchase ? (invoice as PurchaseInvoice) : null;

  const docType = isPurchase ? 'Purchase Voucher' : 'Sales Invoice';
  const docNo = sale ? sale.invoiceNumber : purchase?.purchaseNumber;
  const partyLabel = isPurchase ? 'Supplier' : 'Customer';
  const partyName = sale ? sale.customerName : purchase?.supplierName;

  const itemsText = invoice.items
    .map((item, idx) => {
      const price = 'unitPrice' in item ? item.unitPrice : item.unitCost;
      return `${idx + 1}. ${item.productName} (x${item.quantity}) @ ${settings.currencySymbol}${price.toLocaleString('en-US', { minimumFractionDigits: 2 })} = ${settings.currencySymbol}${item.total.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
    })
    .join('\n');

  let text = `🧾 *${settings.companyName || 'Busy UFO'}*\n`;
  text += `*${docType}:* ${docNo}\n`;
  text += `*Date:* ${invoice.date}\n`;
  text += `*${partyLabel}:* ${partyName}\n`;
  text += `*Type:* ${invoice.type}\n`;
  text += `------------------------------\n`;
  text += `*Items:*\n${itemsText}\n`;
  text += `------------------------------\n`;
  text += `*Grand Total:* ${settings.currencySymbol}${invoice.grandTotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}\n`;
  text += `*Paid Amount:* ${settings.currencySymbol}${invoice.paidAmount.toLocaleString('en-US', { minimumFractionDigits: 2 })}\n`;
  if (invoice.dueAmount > 0) {
    text += `*Balance Due:* ${settings.currencySymbol}${invoice.dueAmount.toLocaleString('en-US', { minimumFractionDigits: 2 })}\n`;
  }
  if (settings.invoiceNote) {
    text += `\n_${settings.invoiceNote}_\n`;
  }
  if (settings.companyPhone) {
    text += `\nContact: ${settings.companyPhone}`;
  }

  return text;
};

export const shareInvoiceViaWhatsApp = (
  invoice: SaleInvoice | PurchaseInvoice,
  isPurchase: boolean,
  settings: AppSettings,
  phone?: string
) => {
  const text = formatInvoiceWhatsAppText(invoice, isPurchase, settings);
  const cleanPhone = phone ? phone.replace(/[^0-9]/g, '') : '';
  const url = cleanPhone
    ? `https://wa.me/${cleanPhone}?text=${encodeURIComponent(text)}`
    : `https://wa.me/?text=${encodeURIComponent(text)}`;
  window.open(url, '_blank');
};

export const shareReportViaWhatsApp = (
  reportTitle: string,
  summaryLines: string[],
  settings: AppSettings,
  phone?: string
) => {
  let text = `📊 *${settings.companyName || 'Busy UFO'}*\n`;
  text += `*${reportTitle}*\n`;
  text += `*Date:* ${new Date().toISOString().split('T')[0]}\n`;
  text += `------------------------------\n`;
  text += summaryLines.join('\n');
  text += `\n------------------------------\n`;
  text += `_Generated by Busy UFO_`;

  const cleanPhone = phone ? phone.replace(/[^0-9]/g, '') : '';
  const url = cleanPhone
    ? `https://wa.me/${cleanPhone}?text=${encodeURIComponent(text)}`
    : `https://wa.me/?text=${encodeURIComponent(text)}`;
  window.open(url, '_blank');
};
